# return all equipments
GET http://localhost:3000/equipment

###

# return equipment at Charing Cross
GET http://localhost:3000/gyms/31/equipment
GET curl http://localhost:3000/gyms/31/equipment | jq



