services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gymapp
    ports:
      - '5432:5432'
    volumes:
      - gymapp_data:/var/lib/postgresql/data

volumes:
  gymapp_data:
